---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Workshop Tips"
      solveButton: false
    - name: module-02
      label: "Exploring the web-UI and Dashboard"
      solveButton: false
    - name: module-03
      label: "Creating an Inventory"
      solveButton: true
    - name: module-04
      label: "Creating your first Project"
      solveButton: true
    - name: module-05
      label: "Get to know Credentials"
      solveButton: true
    - name: module-06
      label: "Creating a Job Template"
      solveButton: true
    - name: module-07
      label: "Creating a second Project"
      solveButton: true
    - name: module-08
      label: "Creating a second and third Job Template"
      solveButton: true
    - name: module-09
      label: "Creating a Workflow Job Tempalte"
      solveButton: true
    - name: module-10
      label: "Creating a Job Template with a Survey"
      solveButton: true


tabs:
  - name: Automation Controller
    url: https://control-${guid}.${domain}/
  - name: ">_ Terminal"
    url: /wetty


  # - name: Windows RDP
  #   url: https://windows-ironrdp-${guid}.${domain}/
  #   external: false
  # - name: ">_ control"
  #   url: /wetty
  # - name: ">_ node01"
  #   url: /wetty_node01
  # - name: ">_ node02"
  #   url: /wetty_node02
  # - name: ">_ node03"
  #   url: /wetty_node03
  # - name: Cloud (PoC)
  #   url: /cloud
